# Generated by Django 4.2.7 on 2023-12-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('reg_date', models.DateField()),
                ('note', models.TextField()),
            ],
            options={
                'db_table': 'patient',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('patient_id', models.IntegerField(blank=True, null=True)),
                ('symptoms', models.CharField(blank=True, max_length=38, null=True)),
                ('diagnostics', models.CharField(blank=True, max_length=38, null=True)),
            ],
            options={
                'db_table': 'record',
                'managed': True,
            },
        ),
    ]
