# Generated by Django 4.2.7 on 2023-12-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patman', '0003_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('picture', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Upload',
            new_name='UploadImage',
        ),
        migrations.RenameField(
            model_name='uploadimage',
            old_name='name',
            new_name='image',
        ),
    ]
