# Generated by Django 4.2.7 on 2023-12-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patman', '0004_uploadvideo_rename_upload_uploadimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='picture',
            field=models.FileField(upload_to='static/'),
        ),
    ]
